apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecr-example
  template:
    metadata:
      labels:
        app: ecr-example
    spec:
      containers:
      - name: web-app-container
        image: 651706782613.dkr.ecr.eu-south-2.amazonaws.com/miwebapp:latest
        ports:
        - containerPort: 80
          protocol: TCP

